version: 2.1
  
executors:
  amd64:
    machine:
      image: ubuntu-2004:latest
      docker_layer_caching: true
    resource_class: medium
    environment:
      DOCKER_BUILDKIT: 1
    docker:
      - image: cimg/base:stable-20.04
  arm64:
    machine:
      image: ubuntu-2004:latest
      docker_layer_caching: true
    resource_class: arm.medium
    environment:
      DOCKER_BUILDKIT: 1
    docker:
      - image: cimg/base:stable-20.04
commands:
  build:
    parameters:
      arch:
        type: string
    steps:
      - checkout
      - run:
          name: Build a container
          command: |
            if [ "$GITHUB_USERNAME$GITHUB_TOKEN" ]
             then
             apk update && apk add jq
             docker login -u $GITHUB_USERNAME -p $GITHUB_TOKEN
             docker build -t ghcr.io/$GITHUB_USER/misskey:latest .
             docker tag ghcr.io/$GITHUB_USERNAME/misskey ghcr.io/$GITHUB_USERNAME/misskey:<< parameters.arch >>-${CIRCLE_SHA1}
             docker push -a ghcr.io/$GITHUB_USERNAME/misskey:latest
            else
             echo -e '\033[0;33mAborted deploying to Docker Hub\033[0;39m'
            fi
jobs:
  build_amd64:
    executor: amd64
    steps:
      - build:
          arch: amd64
  build_arm64:
    executor: arm64
    steps:
      - build:
          arch: arm64
  deploy:
    docker:
      - image: ghcr.io/$GITHUB_USERNAME/misskey:latest
        auth:
          username: $GITHUB_USERNAME
          password: $GITHUB_TOKEN
    executor: amd64
    steps:
     - run:
        name: "Create manifest"
        command: |
          docker manifest create ragujp/misskey:latest \
            --amend ragujp/misskey:amd64-${CIRCLE_SHA1} \
            --amend ragujp/misskey:arm64-${CIRCLE_SHA1}
     - run:
        name: "Push manifest"
        command: |
          docker manifest push ragujp/misskey:latest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_amd64
      - build_arm64
      - deploy:
          requires:
            - build_amd64
            - build_arm64
